[package]
name = "rmk-types"
version = "0.1.0"
edition = "2024"
authors = ["Haobo Gu <haobogu@outlook.com>"]
description = "Common types in RMK"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
license = "MIT OR Apache-2.0"
resolver = "2"

[dependencies]
defmt = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }

serde = { version = "1", default-features = false, features = ["derive"] }
postcard = { version = "1", features = ["experimental-derive"] }
strum = { version = "0.27", default-features = false, features = ["derive"] }

bitfield-struct = "0.11"

[features]
default = ["per_key_profile"] #TODO remove per_key_profile from defaults
## If you want to customize each tap hold (TH LT MT) key's profile separately (the positional configuration in matrix map is not enough)
## then you may enable this feature - Warning: it will increase the RAM usage of the keymaps with ROW*COL*LAYER_NUM*32bits
per_key_profile = []

defmt = [
    "dep:defmt",
    "postcard/defmt",
]

